### ISSUE TITLE
Research and Submit to WP Plugin Repository

### ISSUE THREAD

**Issue by n8finch** [Paycove/woocommerce-plugin#8]
**Plugin Developer Info**: https://wordpress.org/plugins/developers/
**Detailed Guidelines**: https://developer.wordpress.org/plugins/wordpress-org/detailed-plugin-guidelines/
**Planning, Submitting, and Maintaining Plugins**: https://developer.wordpress.org/plugins/wordpress-org/planning-submitting-and-maintaining-plugins/

## Highlights
**Readme files**
To make your entry in the plugin browser most useful, each plugin should have a readme file named readme.txt that adheres to the [WordPress plugin readme file standard](https://wordpress.org/plugins/readme.txt). You can put your readme file through the [readme validator](https://wordpress.org/plugins/developers/readme-validator/) to check it.

**Licence**
Your plugin must be compatible with the [GNU General Public License v2](https://www.gnu.org/licenses/license-list.html#GPLCompatibleLicenses), or any later version. We strongly recommend using the same license as WordPress — “GPLv2 or later.”... For a specific list of compatible licenses, please read the [GPL-Compatible license list](https://www.gnu.org/philosophy/license-list.html#GPLCompatibleLicenses) on gnu.org.

## Todos

- [ ] Decide on a license: @jeffreygluck , can you own that subtask? Let me know if you want me to create an Issue for you on that
- [ ] We need a primary email to use for this, maybe wordpress@paycove.io? @jeffreygluck can you own that subtask? Let me know if you want me to create an Issue for you on that
- [ ] Get a minimum version submitted to the repo

**Note:** It looks like there's a minimum 14 day waiting period for plugin approvals, and there will most likely be plenty of back and forth. Avado or anyone else can always install the zip file directly, but we'll want to make sure that their plugin has a folder slug like `wp-paycove-avado` or something like that. That way, they'll be able to install the plugin from the WP Repo eventually, and it won't conflict with what they're using. We can also send them zip files to update with, or give them their own repository.
